import { projects, profile } from './content.mjs';
import { escapeHtml, link, projectImage, projectPath, contactCta } from './components.mjs';

export function caseStudy(project) {
  return `<article class="case-study"><header class="case-header shell"><a class="back-link" href="/#proyectos">← Todos los proyectos</a><p class="eyebrow">${project.type} / ${project.category}</p><h1>${project.name}<span>${project.discipline}</span></h1><p class="case-headline">${project.headline}</p><div class="case-meta"><span>Diseño y desarrollo · Aymar Salgado</span>${link(project.url, project.slug === 'viaja' ? 'Ver código en GitHub' : 'Visitar web publicada', 'button primary')}</div></header>
  <figure class="case-cover ${project.color}"><div class="shell"><div class="browser-frame"><div class="browser-bar"><span>● ● ●</span><span>${project.slug === 'viaja' ? 'VIAJA / Pantalla de bienvenida' : new URL(project.url).hostname}</span></div>${projectImage(project, { eager: true })}</div></div><figcaption class="shell">${project.galleryCaption}</figcaption></figure>
  <div class="case-body shell"><aside><p class="eyebrow">Dentro del proyecto</p><nav aria-label="Contenido del caso de estudio"><a href="#contexto">Contexto</a><a href="#solucion">Solución</a><a href="#desarrollo">Desarrollo</a><a href="#stack">Tecnologías</a><a href="#resultado">Resultado</a></nav></aside><div class="case-prose"><section id="contexto"><p class="eyebrow">01 / Contexto</p><h2>El punto de partida.</h2><p>${project.context}</p><h3>La necesidad</h3><p>${project.need}</p></section><section id="solucion"><p class="eyebrow">02 / Solución</p><h2>Lo que construí.</h2><p class="lead">${project.solution}</p></section><section id="desarrollo"><p class="eyebrow">03 / Desarrollo</p><h2>Las decisiones que le dan forma.</h2>${project.details.map(([title, description]) => `<div class="case-detail"><h3>${title}</h3><p>${description}</p></div>`).join('')}${project.slug === 'viaja' ? architecture() : ''}</section><section id="stack"><p class="eyebrow">04 / Tecnologías</p><h2>La base del proyecto.</h2><ul class="tech-list">${project.stack.map((tech) => `<li>${escapeHtml(tech)}</li>`).join('')}</ul><p class="small-note">${project.stackNote}</p></section><section id="resultado"><p class="eyebrow">05 / Resultado</p><h2>Un producto concreto.</h2><p>${project.result}</p>${link(project.url, project.slug === 'viaja' ? 'Explorar el repositorio' : 'Explorar la web')}</section></div></div></article>
  ${contactCta()}<nav class="other-projects shell" aria-label="Otros proyectos"><p class="eyebrow">Sigue explorando</p>${projects
    .filter((item) => item.slug !== project.slug)
    .map((item) => link(projectPath(item.slug), item.name))
    .join('')}</nav>`;
}

function architecture() {
  return `<figure class="architecture"><figcaption>Arquitectura verificada en el código</figcaption><div class="architecture-client"><strong>Vue + Inertia</strong><span>Interfaz y navegación</span></div><div class="architecture-core"><strong>Laravel</strong><span>Validación, autenticación y lógica</span></div><div class="architecture-services"><div><strong>MySQL</strong><span>Usuarios y viajes</span></div><div><strong>Gemini</strong><span>Itinerarios JSON</span></div><div><strong>Redis</strong><span>Caché</span></div></div><p>El backend también consulta Unsplash y genera PDF con Dompdf.</p></figure>`;
}

export function privacy() {
  return `<article class="legal shell section-space"><p class="eyebrow">Información de privacidad</p><h1>Una web sencilla.<br>Un contacto directo.</h1><p>Este portfolio pertenece a ${profile.name}. Para cualquier consulta relacionada con tus datos, puedes escribir a <a href="mailto:${profile.email}">${profile.email}</a>.</p><h2>El asistente de contacto</h2><p>Los campos se procesan en tu navegador para preparar un borrador. Esta web no almacena esos datos, no los envía a un servidor y no confirma ningún envío. Si eliges abrir Gmail o tu aplicación de correo, el nombre y el texto del proyecto se transfieren a ese servicio para que puedas revisarlos y enviarlos.</p><h2>Si me escribes</h2><p>Usaré la información que compartas para responder a tu consulta y, si corresponde, preparar una propuesta sobre el proyecto que solicitas. Se conservará durante la gestión de esa conversación y los plazos que puedan resultar aplicables si se inicia una relación profesional. Puedes solicitar acceso, rectificación o supresión escribiendo al mismo correo.</p><h2>Alojamiento y enlaces</h2><p>La web se aloja en GitHub Pages. El proveedor puede tratar datos técnicos de conexión conforme a su política. No se han incorporado herramientas de analítica, cookies de seguimiento ni fuentes de terceros. Al abrir enlaces externos se aplican las políticas de esos sitios.</p>${link('https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement', 'Privacidad de GitHub')}${link('/', 'Volver al inicio')}</article>`;
}
