import { profile, projects, services } from './content.mjs';
import { arrow, link, projectImage, projectPath } from './components.mjs';

function blueprint() {
  return `<div class="blueprint" role="group" aria-label="Explora las capas de un producto digital">
    <div class="blueprint-top"><span class="eyebrow">De necesidad a producto</span><span class="small-label" aria-hidden="true">01—03</span></div>
    <div class="layer-illustration" aria-hidden="true"><div class="plane plane-data"><span>03 / DATOS</span><div class="data-bars"><i></i><i></i><i></i><i></i></div></div><div class="plane plane-logic"><span>02 / LÓGICA</span><div class="logic-path"><i></i><b>ƒ</b><i></i></div></div><div class="plane plane-interface"><span>01 / INTERFAZ</span><div class="wireframe"><i></i><b></b><em></em><em></em><em></em></div></div><span class="axis axis-x">x</span><span class="axis axis-y">y</span></div>
    <div class="blueprint-caption"><span class="status-dot" aria-hidden="true"></span><span id="blueprint-description">Una interfaz clara para que tu negocio se entienda.</span></div>
    <div class="blueprint-controls" role="group" hidden aria-label="Explorar tipos de producto"><button type="button" data-layer="web" aria-pressed="true">Web</button><button type="button" data-layer="app" aria-pressed="false">Aplicación</button><button type="button" data-layer="api" aria-pressed="false">Integración</button></div>
    <p class="blueprint-proof">En la práctica: <a id="blueprint-project" href="/proyectos/jose-vale/"><span>José Vale</span> ${arrow}</a></p>
  </div>`;
}

function work() {
  const [jose, nereida, viaja] = projects;
  return `<section id="proyectos" class="work shell section-space"><div class="section-heading"><div><p class="eyebrow"><span>01 /</span> Trabajo seleccionado</p><h2>Menos promesas.<br><em>Más producto.</em></h2></div><p>Webs para negocios reales y una aplicación que conecta frontend, backend e inteligencia artificial.</p></div>
    <article class="project project-featured"><a class="project-visual jose" href="${projectPath(jose.slug)}" aria-label="Ver caso de estudio de José Vale"><span class="visual-label">Web profesional / Cliente real</span><div class="browser-frame"><div class="browser-bar"><span class="browser-dots" aria-hidden="true"><i></i><i></i><i></i></span><span>josevaleosteopata.es</span>${arrow}</div>${projectImage(jose)}</div><span class="project-open" aria-hidden="true">Explorar proyecto ${arrow}</span></a><div class="project-caption"><div><p class="eyebrow">01 — Diseño y desarrollo web</p><h3><a href="${projectPath(jose.slug)}">José Vale<span> / Osteopatía</span></a></h3></div><p>${jose.summary}</p>${link(projectPath(jose.slug), 'Ver caso de estudio')}</div></article>
    <div class="project-pair"><article class="project"><a class="project-visual nereida" href="${projectPath(nereida.slug)}" aria-label="Ver caso de estudio de Nereida Soria"><span class="visual-label">Web de servicios / Cliente real</span><div class="browser-frame"><div class="browser-bar"><span class="browser-dots" aria-hidden="true"><i></i><i></i><i></i></span><span>nereidaquiromasajista.es</span></div>${projectImage(nereida, { sizes: '(max-width: 760px) 92vw, 48vw' })}</div><span class="project-open" aria-hidden="true">Explorar proyecto ${arrow}</span></a><div class="project-caption"><div><p class="eyebrow">02 — Diseño y desarrollo web</p><h3><a href="${projectPath(nereida.slug)}">Nereida Soria</a></h3></div><p>${nereida.summary}</p>${link(projectPath(nereida.slug), 'Ver caso de estudio')}</div></article>
    <article class="project project-software"><a class="project-visual viaja" href="${projectPath(viaja.slug)}" aria-label="Ver caso de estudio de VIAJA"><span class="visual-label">Aplicación web / Proyecto final DAW</span><div class="browser-frame"><div class="browser-bar"><span class="browser-dots" aria-hidden="true"><i></i><i></i><i></i></span><span>VIAJA / Itinerarios inteligentes</span></div>${projectImage(viaja, { sizes: '(max-width: 760px) 92vw, 48vw' })}</div><span class="project-open" aria-hidden="true">Explorar arquitectura ${arrow}</span></a><div class="project-caption"><div><p class="eyebrow">03 — Software e inteligencia artificial</p><h3><a href="${projectPath(viaja.slug)}">VIAJA</a></h3></div><p>${viaja.summary}</p>${link(projectPath(viaja.slug), 'Ver caso de estudio')}</div></article></div>
    <div class="section-tail"><p>Una web, una aplicación, una necesidad concreta.</p>${link('#contacto', 'Hablemos de la tuya')}</div></section>`;
}

function serviceSection() {
  return `<section id="servicios" class="services section-space"><div class="shell"><div class="section-heading"><div><p class="eyebrow"><span>02 /</span> Qué puedo construir</p><h2>El punto de partida<br>es lo que <em>necesitas.</em></h2></div><p>La tecnología viene después. Primero, qué quieres resolver y para quién.</p></div><div class="service-list">${services.map(([n, title, name, description, slug]) => `<article class="service-row"><span class="service-number">${n}</span><div><h3>${title}</h3><p class="service-name">${name}</p></div><p>${description}</p><a class="service-proof" href="${projectPath(slug)}" aria-label="Ver proyecto relacionado con ${name}">Ver ejemplo ${arrow}</a></article>`).join('')}</div><div class="section-tail"><p>¿Todavía no sabes qué solución necesitas? Podemos empezar por ahí.</p>${link('#contacto', 'Cuéntame el problema', 'button primary')}</div></div></section>`;
}

function about() {
  return `<section id="sobre-mi" class="about shell section-space"><p class="eyebrow"><span>03 /</span> Detrás del código</p><div class="about-grid"><div><h2>Base de desarrollador.<br><em>Mirada de producto.</em></h2><p class="about-intro">Soy Aymar Salgado Dieguez. Construyo webs y aplicaciones, y sigo ampliando lo que puedo hacer con ellas.</p><p>Me gradué en Desarrollo de Aplicaciones Web en el IES Fernando Wirtz. Actualmente estudio el Grado en Inteligencia Artificial en la Universidade da Coruña y compagino mi formación con proyectos de desarrollo.</p><p>Me interesa el recorrido completo: entender una necesidad, darle forma en una interfaz y construir el software que la hace funcionar.</p>${link(profile.github, 'Explorar mi código')}</div><div id="experiencia" class="experience"><p class="eyebrow">Experiencia y formación</p><article><span class="experience-marker"></span><p class="small-label">Prácticas profesionales · Finalizadas</p><h3>Indra / Minsait</h3><p class="role">Software Analyst & Developer</p><p>Participación en el análisis, diseño y desarrollo de soluciones de software durante mis prácticas profesionales.</p></article><article><p class="small-label">Actualmente</p><h3>Inteligencia Artificial</h3><p>Grado · Universidade da Coruña</p></article><article><p class="small-label">Formación completada</p><h3>Desarrollo de Aplicaciones Web</h3><p>IES Fernando Wirtz</p></article><details><summary>Antes del desarrollo</summary><p>En Correos trabajé en logística y reparto, con organización autónoma de rutas. En McDonald’s, en atención al cliente y coordinación en equipo. Experiencias que aportan contexto a mi forma de trabajar.</p></details></div></div>
  <div id="habilidades" class="stack"><div><p class="eyebrow">Tecnología con contexto</p><p>Herramientas que puedes encontrar en mi código.</p></div><dl><div><dt>Interfaces</dt><dd>Vue.js · JavaScript · Tailwind CSS</dd></div><div><dt>Aplicaciones y datos</dt><dd>Laravel · PHP · Inertia.js · MySQL</dd></div><div><dt>Integraciones</dt><dd>Gemini API · Unsplash API · Redis</dd></div><div><dt>Base de programación</dt><dd>Python · Java · SQL</dd></div></dl></div></section>`;
}

function process() {
  const steps = [
    [
      'Entender',
      'Hablamos de tu idea, del contexto y de lo que debe resolver. Definimos un alcance realista.',
    ],
    ['Diseñar', 'Ordenamos contenido y recorridos. La interfaz tiene que ayudar a usar el producto.'],
    ['Construir', 'Desarrollo la solución y revisamos cómo funciona, también en móvil.'],
    [
      'Entregar',
      'Comprobamos el resultado y dejamos claros su uso, mantenimiento y posibles siguientes pasos.',
    ],
  ];
  return `<section class="process shell section-space"><div class="section-heading"><div><p class="eyebrow">Una forma de trabajar</p><h2>De la primera conversación<br>a algo que <em>puedas usar.</em></h2></div></div><ol>${steps.map(([title, desc], i) => `<li><span class="step-number">0${i + 1}</span><h3>${title}</h3><p>${desc}</p></li>`).join('')}</ol></section>`;
}

function contact() {
  return `<section id="contacto" class="contact section-space"><div class="shell contact-grid"><div><p class="eyebrow"><span>04 /</span> Empecemos por una conversación</p><h2>¿Qué necesitas<br><em>construir?</em></h2><p>Una nueva web, un rediseño, una aplicación o una herramienta para tu día a día. Cuéntame dónde estás y qué quieres resolver.</p><a class="contact-email" href="mailto:${profile.email}"><span>${profile.email}</span>${arrow}</a><button id="copy-email" class="text-button" type="button" hidden>Copiar dirección</button><p id="email-copy-status" class="copy-status" role="status"></p><div class="contact-socials">${link(profile.linkedin, 'LinkedIn')}${link(profile.github, 'GitHub')}</div></div>
    <div class="contact-brief"><h3>Cuéntame tu idea.</h3><p>Escribe unas líneas y prepara el mensaje. Después podrás abrirlo en tu correo o copiarlo.</p><form id="project-form" aria-describedby="contact-note" hidden><label for="project-kind">¿Qué tienes en mente?</label><select id="project-kind" name="kind"><option>Web profesional</option><option>Landing page</option><option>Aplicación web</option><option>Software a medida</option><option>Integración o IA</option><option>Quiero explorar una idea</option></select><label for="project-name">¿Cómo te llamas?</label><input id="project-name" name="name" autocomplete="name" required maxlength="80" placeholder="Tu nombre"><label for="project-message">¿Qué te gustaría resolver?</label><textarea id="project-message" name="message" rows="3" required minlength="15" maxlength="1500" placeholder="Cuéntame la idea, para quién es y en qué punto está."></textarea><button class="button primary" type="submit">Preparar mensaje ${arrow}</button><p class="form-note" id="contact-note">Estos datos no se envían ni se guardan en la web. <a href="/privacidad/">Privacidad</a></p></form><noscript><p>Escríbeme qué necesitas, para quién es y en qué punto está tu proyecto.</p>${link(`mailto:${profile.email}`, 'Escribir un correo', 'button primary')}</noscript><div id="draft-result" hidden><h3 id="draft-heading" tabindex="-1">Tu mensaje está listo.</h3><p>Último paso: ábrelo en tu correo y pulsa Enviar allí.</p><dl class="draft-meta"><div><dt>Para</dt><dd>${profile.email}</dd></div><div><dt>Asunto</dt><dd id="draft-subject"></dd></div></dl><label for="draft-preview">Mensaje preparado</label><textarea id="draft-preview" rows="8" readonly></textarea><div class="draft-actions"><a id="draft-gmail" class="button primary" href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;to=${profile.email}" target="_blank" rel="noopener noreferrer">Abrir en Gmail ${arrow}</a><a id="draft-email" class="text-link" href="mailto:${profile.email}">Usar mi aplicación de correo ${arrow}</a><button id="copy-draft" class="text-button" type="button">Copiar mensaje</button></div><p class="form-note">Si no se abre tu correo, copia el mensaje y envíalo a la dirección indicada.</p><p id="draft-status" class="copy-status" role="status"></p><button id="edit-brief" class="text-button" type="button">Editar mi idea</button></div></div></div></section>`;
}

export function home() {
  return `<section id="inicio" class="hero shell"><div class="hero-copy"><p class="eyebrow"><span class="status-dot" aria-hidden="true"></span> Desarrollo web & software</p><h1>Tu próximo paso.<br><em>Bien construido.</em></h1><p class="hero-description">Desarrollo webs y aplicaciones para negocios, profesionales e ideas que necesitan funcionar.</p><p class="hero-person">Soy Aymar, <strong>graduado en Desarrollo de Aplicaciones Web (DAW)</strong> por el IES Fernando Wirtz. Actualmente amplío mi formación con el Grado en Inteligencia Artificial en la UDC.</p><div class="hero-actions">${link('#contacto', 'Cuéntame tu proyecto', 'button primary')}${link('#proyectos', 'Ver mi trabajo')}</div><p class="availability"><span class="availability-line" aria-hidden="true"></span> Abierto a proyectos freelance y colaboraciones</p></div>${blueprint()}<div class="hero-bottom"><span>Del primer boceto al último detalle.</span><a href="#proyectos">Explora el trabajo ${arrow}</a></div></section>
  <div class="credentials shell" role="group" aria-label="Trayectoria"><div><span>Formación</span><strong>Graduado en DAW</strong></div><div><span>Especialización en curso</span><strong>Inteligencia Artificial · UDC</strong></div><div><span>Prácticas de desarrollo</span><strong>Indra / Minsait</strong></div><div><span>Trabajo publicado</span><strong>Proyectos para clientes reales</strong></div></div>
  ${work()}${serviceSection()}${about()}${process()}${contact()}`;
}
